import 'package:flutter/material.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone836widget/generated/GeneratedGroup18941Widget.dart';

/* Frame iPhone 8 - 36
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone836Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: GestureDetector(
      onTap: () => Navigator.pushNamed(context, '/GeneratedIPhone819Widget'),
      child: Container(
        decoration: BoxDecoration(
          boxShadow: [
            BoxShadow(
              color: Color.fromARGB(76, 10, 1, 112),
              offset: Offset(30.0, 30.0),
              blurRadius: 35.0,
            )
          ],
        ),
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Container(
            width: 375.0,
            height: 667.0,
            child: Stack(
                fit: StackFit.expand,
                alignment: Alignment.center,
                overflow: Overflow.visible,
                children: [
                  ClipRRect(
                    borderRadius: BorderRadius.zero,
                    child: Container(
                      color: Color.fromARGB(255, 49, 141, 193),
                    ),
                  ),
                  Positioned(
                    left: 133.0,
                    top: 281.0,
                    right: null,
                    bottom: null,
                    width: 109.0,
                    height: 104.0,
                    child: GeneratedGroup18941Widget(),
                  )
                ]),
          ),
        ),
      ),
    ));
  }
}
