import 'package:flutter/material.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone827widget/generated/GeneratedGroup1912Widget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone827widget/generated/GeneratedGroup1877Widget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone827widget/generated/GeneratedSubmitWidget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone827widget/generated/GeneratedWehavesentthecodeverificationtoYourMailIDWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone827widget/generated/GeneratedEnterotpcuateWidget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone827widget/generated/GeneratedOTPWidget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone827widget/generated/GeneratedGroup1911Widget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone827widget/generated/GeneratedVerificationCodeWidget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone827widget/generated/GeneratedOTPnotrecivedRESENDWidget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone827widget/generated/GeneratedGroup1909Widget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone827widget/generated/GeneratedRectangle6Widget2.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone827widget/generated/GeneratedGroup1910Widget.dart';

/* Frame iPhone 8 - 27
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone827Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(76, 10, 1, 112),
            offset: Offset(30.0, 30.0),
            blurRadius: 35.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 667.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 244, 250, 255),
                  ),
                ),
                Positioned(
                  left: 168.0,
                  top: 74.0,
                  right: null,
                  bottom: null,
                  width: 44.0,
                  height: 28.0,
                  child: GeneratedOTPWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.037333333333333336;

                    final double height =
                        constraints.maxHeight * 0.020989505247376312;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.06933333333333333,
                          y: constraints.maxHeight * 0.1184407796101949,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroup1877Widget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.51863916015625;

                    final double height =
                        constraints.maxHeight * 0.3066679855872845;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.24,
                          y: constraints.maxHeight * 0.17541229385307347,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedEnterotpcuateWidget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 77.0,
                  top: 458.0,
                  right: null,
                  bottom: null,
                  width: 40.0,
                  height: 40.0,
                  child: GeneratedGroup1909Widget(),
                ),
                Positioned(
                  left: 137.0,
                  top: 458.0,
                  right: null,
                  bottom: null,
                  width: 40.0,
                  height: 40.0,
                  child: GeneratedGroup1910Widget(),
                ),
                Positioned(
                  left: 197.0,
                  top: 458.0,
                  right: null,
                  bottom: null,
                  width: 40.0,
                  height: 40.0,
                  child: GeneratedGroup1911Widget(),
                ),
                Positioned(
                  left: 257.0,
                  top: 458.0,
                  right: null,
                  bottom: null,
                  width: 40.0,
                  height: 40.0,
                  child: GeneratedGroup1912Widget(),
                ),
                Positioned(
                  left: 132.0,
                  top: 546.0,
                  right: null,
                  bottom: null,
                  width: 110.0,
                  height: 35.0,
                  child: GeneratedRectangle6Widget2(),
                ),
                Positioned(
                  left: 109.0,
                  top: 353.0,
                  right: null,
                  bottom: null,
                  width: 158.0,
                  height: 25.0,
                  child: GeneratedVerificationCodeWidget(),
                ),
                Positioned(
                  left: 71.0,
                  top: 401.0,
                  right: null,
                  bottom: null,
                  width: 234.0,
                  height: 34.0,
                  child:
                      GeneratedWehavesentthecodeverificationtoYourMailIDWidget(),
                ),
                Positioned(
                  left: 161.5625,
                  top: 557.0,
                  right: null,
                  bottom: null,
                  width: 50.21875,
                  height: 12.15625,
                  child: GeneratedSubmitWidget(),
                ),
                Positioned(
                  left: 118.0,
                  top: 517.0,
                  right: null,
                  bottom: null,
                  width: 141.0,
                  height: 16.0,
                  child: GeneratedOTPnotrecivedRESENDWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
