import 'package:flutter/material.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone828widget/generated/GeneratedNewPasswordWidget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone828widget/generated/GeneratedCreateanewpasswordWidget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone828widget/generated/GeneratedPleaseresetyouraccountpasswordWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone828widget/generated/GeneratedResetPasswordWidget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone828widget/generated/GeneratedRectangle6Widget1.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone828widget/generated/GeneratedRectangle618Widget1.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone828widget/generated/GeneratedConformPasswordWidget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone828widget/generated/GeneratedRectangleWidget3.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone828widget/generated/GeneratedRectangleWidget2.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone828widget/generated/GeneratedRectangle619Widget3.dart';

/* Frame iPhone 8 - 28
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone828Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(76, 10, 1, 112),
            offset: Offset(30.0, 30.0),
            blurRadius: 35.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 667.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 244, 250, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.8933333333333333;

                    final double height =
                        constraints.maxHeight * 0.0704647676161919;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.9466666666666667,
                          y: constraints.maxHeight * 0.48125937031484256,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedRectangle618Widget1(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.8933333333333333;

                    final double height =
                        constraints.maxHeight * 0.0704647676161919;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.9466666666666667,
                          y: constraints.maxHeight * 0.5817091454272864,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedRectangle619Widget3(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 98.0,
                  top: 44.0,
                  right: null,
                  bottom: null,
                  width: 178.0,
                  height: 178.0,
                  child: GeneratedRectangleWidget2(),
                ),
                Positioned(
                  left: 107.0,
                  top: 460.0,
                  right: null,
                  bottom: null,
                  width: 161.0,
                  height: 35.0,
                  child: GeneratedRectangle6Widget1(),
                ),
                Positioned(
                  left: 98.0,
                  top: 40.0,
                  right: null,
                  bottom: null,
                  width: 178.0,
                  height: 178.0,
                  child: GeneratedRectangleWidget3(),
                ),
                Positioned(
                  left: 83.0,
                  top: 236.0,
                  right: null,
                  bottom: null,
                  width: 211.0,
                  height: 25.0,
                  child: GeneratedCreateanewpasswordWidget(),
                ),
                Positioned(
                  left: 58.0,
                  top: 277.0,
                  right: null,
                  bottom: null,
                  width: 260.0,
                  height: 21.0,
                  child: GeneratedPleaseresetyouraccountpasswordWidget(),
                ),
                Positioned(
                  left: 40.0,
                  top: 404.0,
                  right: null,
                  bottom: null,
                  width: 123.0,
                  height: 18.0,
                  child: GeneratedConformPasswordWidget(),
                ),
                Positioned(
                  left: 40.0,
                  top: 337.0,
                  right: null,
                  bottom: null,
                  width: 96.0,
                  height: 18.0,
                  child: GeneratedNewPasswordWidget(),
                ),
                Positioned(
                  left: 130.0859375,
                  top: 471.0,
                  right: null,
                  bottom: null,
                  width: 113.6953125,
                  height: 12.15625,
                  child: GeneratedResetPasswordWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
