import 'package:flutter/material.dart';

/* Frame Group 1928
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedGroup1928Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: ClipRRect(
      borderRadius: BorderRadius.zero,
      child: Container(
        width: 334.1051330566406,
        height: 604.1050415039062,
        child: ClipRRect(
          borderRadius: BorderRadius.zero,
          child: Image.asset(
            "assets/images/49693a46376971fa9450b8bb56e9fbe75f92da8a.png",
            color: null,
            fit: BoxFit.cover,
            width: 334.1051330566406,
            height: 604.1050415039062,
            colorBlendMode: BlendMode.dstATop,
          ),
        ),
      ),
    ));
  }
}
