import 'package:flutter/material.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone819widget/generated/GeneratedForgetPasswordWidget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone819widget/generated/GeneratedPasswordWidget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone819widget/generated/GeneratedRectangle618Widget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone819widget/generated/GeneratedYourEmailWidget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone819widget/generated/GeneratedRectangleWidget1.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone819widget/generated/GeneratedGroup1897Widget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone819widget/generated/GeneratedWelcomeBackWidget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone819widget/generated/GeneratedGroup1887Widget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone819widget/generated/GeneratedRectangle619Widget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone819widget/generated/GeneratedContinueWithGoogleWidget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone819widget/generated/GeneratedPleaseLogintoyourexistingaccountWidget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone819widget/generated/GeneratedRectangleWidget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone819widget/generated/GeneratedGroup1898Widget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone819widget/generated/GeneratedORWidget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone819widget/generated/GeneratedGroup1899Widget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone819widget/generated/GeneratedContinueWithMailWidget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone819widget/generated/GeneratedGroup1888Widget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone819widget/generated/GeneratedLoginWidget.dart';

/* Frame iPhone 8 - 19
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone819Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(76, 10, 1, 112),
            offset: Offset(30.0, 30.0),
            blurRadius: 35.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 667.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 244, 250, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.8933333333333333;

                    final double height =
                        constraints.maxHeight * 0.0704647676161919;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.9466666666666667,
                          y: constraints.maxHeight * 0.48125937031484256,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedRectangle618Widget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.8933333333333333;

                    final double height =
                        constraints.maxHeight * 0.0704647676161919;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.9466666666666667,
                          y: constraints.maxHeight * 0.5817091454272864,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedRectangle619Widget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 135.0,
                  top: 461.0,
                  right: null,
                  bottom: null,
                  width: 105.0,
                  height: 35.0,
                  child: GeneratedGroup1897Widget(),
                ),
                Positioned(
                  left: 99.0,
                  top: 44.0,
                  right: null,
                  bottom: null,
                  width: 178.0,
                  height: 178.0,
                  child: GeneratedRectangleWidget(),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.5413333333333333;

                    final double height =
                        constraints.maxHeight * 0.046476781636342474;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.22933333333333333,
                          y: constraints.maxHeight * 0.8140929535232384,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroup1898Widget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.5413333333333333;

                    final double height =
                        constraints.maxHeight * 0.046476781636342474;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.22933333333333333,
                          y: constraints.maxHeight * 0.9070464767616192,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedGroup1899Widget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 98.0,
                  top: 40.0,
                  right: null,
                  bottom: null,
                  width: 178.0,
                  height: 178.0,
                  child: GeneratedRectangleWidget1(),
                ),
                Positioned(
                  left: 55.0,
                  top: 284.0,
                  right: null,
                  bottom: null,
                  width: 268.0,
                  height: 21.0,
                  child: GeneratedPleaseLogintoyourexistingaccountWidget(),
                ),
                Positioned(
                  left: 40.0,
                  top: 337.0,
                  right: null,
                  bottom: null,
                  width: 69.0,
                  height: 18.0,
                  child: GeneratedYourEmailWidget(),
                ),
                Positioned(
                  left: 40.0,
                  top: 404.0,
                  right: null,
                  bottom: null,
                  width: 67.0,
                  height: 21.0,
                  child: GeneratedPasswordWidget(),
                ),
                Positioned(
                  left: 165.0,
                  top: 468.0,
                  right: null,
                  bottom: null,
                  width: 50.0,
                  height: 26.0,
                  child: GeneratedLoginWidget(),
                ),
                Positioned(
                  left: 138.0,
                  top: 511.0,
                  right: null,
                  bottom: null,
                  width: 101.0,
                  height: 16.0,
                  child: GeneratedForgetPasswordWidget(),
                ),
                Positioned(
                  left: 132.55813598632812,
                  top: 551.0,
                  right: null,
                  bottom: null,
                  width: 124.0,
                  height: 17.0,
                  child: GeneratedContinueWithMailWidget(),
                ),
                Positioned(
                  left: 132.55813598632812,
                  top: 613.0,
                  right: null,
                  bottom: null,
                  width: 138.0,
                  height: 17.0,
                  child: GeneratedContinueWithGoogleWidget(),
                ),
                Positioned(
                  left: 105.0,
                  top: 547.0,
                  right: null,
                  bottom: null,
                  width: 23.604650497436523,
                  height: 22.14285659790039,
                  child: GeneratedGroup1887Widget(),
                ),
                Positioned(
                  left: 105.0,
                  top: 609.0,
                  right: null,
                  bottom: null,
                  width: 23.604650497436523,
                  height: 22.14285659790039,
                  child: GeneratedGroup1888Widget(),
                ),
                Positioned(
                  left: 181.0,
                  top: 584.0,
                  right: null,
                  bottom: null,
                  width: 19.0,
                  height: 17.0,
                  child: GeneratedORWidget(),
                ),
                Positioned(
                  left: 118.0,
                  top: 247.0,
                  right: null,
                  bottom: null,
                  width: 141.0,
                  height: 25.0,
                  child: GeneratedWelcomeBackWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
