import 'package:flutter/material.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone821widget/generated/GeneratedRectangle620Widget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone821widget/generated/GeneratedRectangleWidget4.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone821widget/generated/GeneratedPleaseSignintoyourNewaccountWidget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone821widget/generated/GeneratedRectangle619Widget5.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone821widget/generated/GeneratedSIGNUPWidget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone821widget/generated/GeneratedRectangle655Widget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone821widget/generated/GeneratedNameWidget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone821widget/generated/GeneratedFluentbattery920regularWidget.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone821widget/generated/GeneratedRectangle618Widget2.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone821widget/generated/GeneratedRectangle619Widget4.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone821widget/generated/GeneratedWelcomeWidget.dart';
import 'package:flutterapp/helpers/transform/transform.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone821widget/generated/GeneratedRectangleWidget5.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone821widget/generated/GeneratedYourEmailWidget1.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone821widget/generated/GeneratedPasswordWidget1.dart';
import 'package:flutterapp/taskmanagerapp/generatediphone821widget/generated/GeneratedConformPasswordWidget1.dart';

/* Frame iPhone 8 - 21
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedIPhone821Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      decoration: BoxDecoration(
        boxShadow: [
          BoxShadow(
            color: Color.fromARGB(76, 10, 1, 112),
            offset: Offset(30.0, 30.0),
            blurRadius: 35.0,
          )
        ],
      ),
      child: ClipRRect(
        borderRadius: BorderRadius.zero,
        child: Container(
          width: 375.0,
          height: 667.0,
          child: Stack(
              fit: StackFit.expand,
              alignment: Alignment.center,
              overflow: Overflow.visible,
              children: [
                ClipRRect(
                  borderRadius: BorderRadius.zero,
                  child: Container(
                    color: Color.fromARGB(255, 244, 250, 255),
                  ),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.8933333333333333;

                    final double height =
                        constraints.maxHeight * 0.0704647676161919;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.9466666666666667,
                          y: constraints.maxHeight * 0.6746626686656672,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedRectangle619Widget4(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.8933333333333333;

                    final double height =
                        constraints.maxHeight * 0.0704647676161919;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.9466666666666667,
                          y: constraints.maxHeight * 0.775112443778111,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedRectangle619Widget5(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.8933333333333333;

                    final double height =
                        constraints.maxHeight * 0.0704647676161919;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.9466666666666667,
                          y: constraints.maxHeight * 0.5742128935532234,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedRectangle618Widget2(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 0.0,
                  top: 0.0,
                  right: 0.0,
                  bottom: 0.0,
                  width: null,
                  height: null,
                  child: LayoutBuilder(builder:
                      (BuildContext context, BoxConstraints constraints) {
                    final double width =
                        constraints.maxWidth * 0.8933333333333333;

                    final double height =
                        constraints.maxHeight * 0.0704647676161919;

                    return Stack(children: [
                      TransformHelper.translate(
                          x: constraints.maxWidth * 0.9466666666666667,
                          y: constraints.maxHeight * 0.4737631184407796,
                          z: 0,
                          child: Container(
                            width: width,
                            height: height,
                            child: GeneratedRectangle620Widget(),
                          ))
                    ]);
                  }),
                ),
                Positioned(
                  left: 40.0,
                  top: 332.0,
                  right: null,
                  bottom: null,
                  width: 43.0,
                  height: 21.0,
                  child: GeneratedNameWidget(),
                ),
                Positioned(
                  left: 318.0,
                  top: 18.0,
                  right: null,
                  bottom: null,
                  width: 30.0,
                  height: 25.0,
                  child: GeneratedFluentbattery920regularWidget(),
                ),
                Positioned(
                  left: 99.0,
                  top: 44.0,
                  right: null,
                  bottom: null,
                  width: 178.0,
                  height: 178.0,
                  child: GeneratedRectangleWidget4(),
                ),
                Positioned(
                  left: 147.0,
                  top: 591.0,
                  right: null,
                  bottom: null,
                  width: 105.0,
                  height: 35.0,
                  child: GeneratedRectangle655Widget(),
                ),
                Positioned(
                  left: 98.0,
                  top: 40.0,
                  right: null,
                  bottom: null,
                  width: 178.0,
                  height: 178.0,
                  child: GeneratedRectangleWidget5(),
                ),
                Positioned(
                  left: 143.0,
                  top: 242.0,
                  right: null,
                  bottom: null,
                  width: 94.0,
                  height: 28.0,
                  child: GeneratedWelcomeWidget(),
                ),
                Positioned(
                  left: 64.0,
                  top: 279.0,
                  right: null,
                  bottom: null,
                  width: 249.0,
                  height: 21.0,
                  child: GeneratedPleaseSignintoyourNewaccountWidget(),
                ),
                Positioned(
                  left: 40.0,
                  top: 399.0,
                  right: null,
                  bottom: null,
                  width: 69.0,
                  height: 18.0,
                  child: GeneratedYourEmailWidget1(),
                ),
                Positioned(
                  left: 40.0,
                  top: 466.0,
                  right: null,
                  bottom: null,
                  width: 67.0,
                  height: 21.0,
                  child: GeneratedPasswordWidget1(),
                ),
                Positioned(
                  left: 40.0,
                  top: 533.0,
                  right: null,
                  bottom: null,
                  width: 123.0,
                  height: 18.0,
                  child: GeneratedConformPasswordWidget1(),
                ),
                Positioned(
                  left: 169.0,
                  top: 599.0,
                  right: null,
                  bottom: null,
                  width: 64.0,
                  height: 21.0,
                  child: GeneratedSIGNUPWidget(),
                )
              ]),
        ),
      ),
    ));
  }
}
