import 'package:flutter/material.dart';
import 'package:flutterapp/taskmanagerapp/generatedframe20widget/generated/GeneratedGroup1924Widget.dart';

/* Frame Frame 20
    Autogenerated by FlutLab FTF Generator
  */
class GeneratedFrame20Widget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Material(
        child: Container(
      width: 335.0,
      height: 47.000030517578125,
      child: Stack(
          fit: StackFit.expand,
          alignment: Alignment.center,
          overflow: Overflow.visible,
          children: [
            Positioned(
              left: 0.0,
              top: 0.0,
              right: null,
              bottom: null,
              width: 335.0,
              height: 47.000030517578125,
              child: GeneratedGroup1924Widget(),
            )
          ]),
    ));
  }
}
